project:
  type: website
  output-dir: docs

website:
  title: "maceydvo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: resume.qmp
        text: Resume
      - href: project.qmd
        text: Projects

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

